[tox]
env_list = test
no_package = true

[testenv:test]
deps = 
    -r openapi/requirements.txt
    pytest
    pytest-django
commands = pytest

[testenv:docdev]
deps = 
    -r openapi/requirements.txt
    sphinx-autobuild
    git+https://github.com/Dog-Egg/sphinx-swaggerui.git
commands = sphinx-autobuild docs docs/_build
