name: Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox coverage

      - name: Test with tox
        run: tox

      - name: Combine coverage data
        run: coverage combine

      - name: Generate coverage report
        run: coverage xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
